<?php

class Project_Brand_Block_Adminhtml_Brand_Edit_Tabs extends Mage_Adminhtml_Block_Widget_Tabs
{
    public function __construct()
    {
        parent::__construct();
        $this->setId('brand_tabs');
        $this->setDestElementId('edit_form');
        $this->setTitle(Mage::helper('project_brand')->__('Brand Information'));
    }

    protected function _beforeToHtml()
    {
        $this->addTab('products', array(
            'label' => Mage::helper('project_brand')->__('Associated products'),
            'url'   => $this->getUrl('*/*/products', array('_current' => true)),
            'class'    => 'ajax'
        ));

        return parent::_beforeToHtml(); // TODO: Change the autogenerated stub
    }
}
