<?php $brands = $this->getBrands(); ?>
<ul>

    <?php foreach ($brands as $brand): ?>
        <li>
            <a href="<?php echo Mage::getUrl('brand/index/view/', array('name' =>$brand->getSlug())); ?>">
                <img width="100" src="<?php echo Mage::helper('project_brand')->getImageUrl($brand->getImageUrl()); ?>" title="<?php echo $brand->getName(); ?>">
            </a>
        </li>
    <?php endforeach; ?>

</ul>