<?php $brand = Mage::registry('brand'); ?>
<?php $products = Mage::registry('products'); ?>

<img src="<?php echo Mage::helper('project_brand')->getImageUrl($brand['image_url']);?>" alt="" style="width:100px; float:right">
<h1><?php echo $brand['name'];?></h1>
<br><hr><br>
<div class="products">
   <?php if(count($products) == 0): ?>
       <h3>No products to show :(</h3>
   <?php endif ?>
    <?php foreach($products as $product): ?>
        <div class="product">
            <a href="<?php echo $product->getProductUrl();?>">
                <p>
                    <img style="width:100px;" src="<?php echo Mage::helper('catalog/image')->init($product, 'thumbnail');?>">
                    <?php echo $product->getName();?>
                </p>
            </a>
        </div>
    <?php endforeach ?>
</div>

<style>
    .product{
        border: 1px dashed #000;
        margin: 1%;
        width: 47%;
        display: inline-block;
        padding: 4px;
        text-align: center;
    }
    .product img {
        display: block;
        margin: 0 auto;
    }
</style>